### ISSUE TITLE
jhead: command not found

### ISSUE THREAD

**Issue by don-smith** [bytespider/resized#1]
It looks like there is a dependency on a tool called `jhead` that's not distributed with this module. I'm not able to get this module to work. Does this sound correct?

**Comment by bytespider** [comment]
This module was/is a WIP.
You'll need the following command line dependencies.

OSX:

```
brew install libjpeg
brew install jhead
brew install netpbm
```

Ubuntu:

```
apt-get install libjpeg
apt-get install jhead
apt-get install netpbm
```

Windows:
You're on your own.

**Comment by don-smith** [comment]
Much thanks for the rapid-fire response!
